void* cupsAddDest () { return 0; }
void* cupsAddDestMediaOptions () { return 0; }
void* cupsAddIntegerOption () { return 0; }
void* cupsAddOption () { return 0; }
void* cupsAdminCreateWindowsPPD () { return 0; }
void* cupsAdminExportSamba () { return 0; }
void* cupsAdminGetServerSettings () { return 0; }
void* cupsAdminSetServerSettings () { return 0; }
void* cupsArrayAdd () { return 0; }
void* _cupsArrayAddStrings () { return 0; }
void* cupsArrayClear () { return 0; }
void* cupsArrayCount () { return 0; }
void* cupsArrayCurrent () { return 0; }
void* cupsArrayDelete () { return 0; }
void* cupsArrayDup () { return 0; }
void* cupsArrayFind () { return 0; }
void* cupsArrayFirst () { return 0; }
void* cupsArrayGetIndex () { return 0; }
void* cupsArrayGetInsert () { return 0; }
void* cupsArrayIndex () { return 0; }
void* cupsArrayInsert () { return 0; }
void* cupsArrayLast () { return 0; }
void* cupsArrayNew () { return 0; }
void* cupsArrayNew2 () { return 0; }
void* cupsArrayNew3 () { return 0; }
void* _cupsArrayNewStrings () { return 0; }
void* cupsArrayNext () { return 0; }
void* cupsArrayPrev () { return 0; }
void* cupsArrayRemove () { return 0; }
void* cupsArrayRestore () { return 0; }
void* cupsArraySave () { return 0; }
void* cupsArrayUserData () { return 0; }
void* cupsBackChannelRead () { return 0; }
void* cupsBackChannelWrite () { return 0; }
void* cupsBackendDeviceURI () { return 0; }
void* cupsBackendReport () { return 0; }
void* _cupsBufferGet () { return 0; }
void* _cupsBufferRelease () { return 0; }
void* cupsCancelDestJob () { return 0; }
void* cupsCancelJob () { return 0; }
void* cupsCancelJob2 () { return 0; }
void* cupsCharsetToUTF8 () { return 0; }
void* cupsCheckDestSupported () { return 0; }
void* cupsCloseDestJob () { return 0; }
void* _cupsCondBroadcast () { return 0; }
void* _cupsCondInit () { return 0; }
void* _cupsCondWait () { return 0; }
void* _cupsConnect () { return 0; }
void* cupsConnectDest () { return 0; }
void* _cupsConvertOptions () { return 0; }
void* cupsCopyDest () { return 0; }
void* cupsCopyDestConflicts () { return 0; }
void* cupsCopyDestInfo () { return 0; }
void* _cupsCreateDest () { return 0; }
void* cupsCreateDestJob () { return 0; }
void* cupsCreateJob () { return 0; }
void* _cups_debug_set () { return 0; }
void* cupsDirClose () { return 0; }
void* cupsDirOpen () { return 0; }
void* cupsDirRead () { return 0; }
void* cupsDirRewind () { return 0; }
void* cupsDoAuthentication () { return 0; }
void* cupsDoFileRequest () { return 0; }
void* cupsDoIORequest () { return 0; }
void* cupsDoRequest () { return 0; }
void* _cupsEncodeOption () { return 0; }
void* cupsEncodeOption () { return 0; }
void* cupsEncodeOptions () { return 0; }
void* cupsEncodeOptions2 () { return 0; }
void* _cupsEncodingName () { return 0; }
void* cupsEncryption () { return 0; }
void* cupsEnumDests () { return 0; }
void* _cupsFileCheck () { return 0; }
void* _cupsFileCheckFilter () { return 0; }
void* cupsFileClose () { return 0; }
void* cupsFileCompression () { return 0; }
void* cupsFileEOF () { return 0; }
void* cupsFileFind () { return 0; }
void* cupsFileFlush () { return 0; }
void* cupsFileGetChar () { return 0; }
void* cupsFileGetConf () { return 0; }
void* cupsFileGetLine () { return 0; }
void* cupsFileGets () { return 0; }
void* cupsFileLock () { return 0; }
void* cupsFileNumber () { return 0; }
void* cupsFileOpen () { return 0; }
void* cupsFileOpenFd () { return 0; }
void* _cupsFilePeekAhead () { return 0; }
void* cupsFilePeekChar () { return 0; }
void* cupsFilePrintf () { return 0; }
void* cupsFilePutChar () { return 0; }
void* cupsFilePutConf () { return 0; }
void* cupsFilePuts () { return 0; }
void* cupsFileRead () { return 0; }
void* cupsFileRewind () { return 0; }
void* cupsFileSeek () { return 0; }
void* cupsFileStderr () { return 0; }
void* cupsFileStdin () { return 0; }
void* cupsFileStdout () { return 0; }
void* cupsFileTell () { return 0; }
void* cupsFileUnlock () { return 0; }
void* cupsFileWrite () { return 0; }
void* cupsFindDestDefault () { return 0; }
void* cupsFindDestReady () { return 0; }
void* cupsFindDestSupported () { return 0; }
void* cupsFinishDestDocument () { return 0; }
void* cupsFinishDocument () { return 0; }
void* cupsFreeDestInfo () { return 0; }
void* cupsFreeDests () { return 0; }
void* cupsFreeJobs () { return 0; }
void* cupsFreeOptions () { return 0; }
void* _cupsGet1284Values () { return 0; }
void* cupsGetClasses () { return 0; }
void* cupsGetConflicts () { return 0; }
void* cupsGetDefault () { return 0; }
void* cupsGetDefault2 () { return 0; }
void* cupsGetDest () { return 0; }
void* cupsGetDestMediaByIndex () { return 0; }
void* cupsGetDestMediaByName () { return 0; }
void* cupsGetDestMediaBySize () { return 0; }
void* cupsGetDestMediaCount () { return 0; }
void* cupsGetDestMediaDefault () { return 0; }
void* _cupsGetDestResource () { return 0; }
void* _cupsGetDests () { return 0; }
void* cupsGetDests () { return 0; }
void* cupsGetDests2 () { return 0; }
void* cupsGetDestWithURI () { return 0; }
void* cupsGetDevices () { return 0; }
void* cupsGetFd () { return 0; }
void* cupsGetFile () { return 0; }
void* cupsGetIntegerOption () { return 0; }
void* cupsGetJobs () { return 0; }
void* cupsGetJobs2 () { return 0; }
void* cupsGetNamedDest () { return 0; }
void* cupsGetOption () { return 0; }
void* _cupsGetPassword () { return 0; }
void* cupsGetPassword () { return 0; }
void* cupsGetPassword2 () { return 0; }
void* cupsGetPPD () { return 0; }
void* cupsGetPPD2 () { return 0; }
void* cupsGetPPD3 () { return 0; }
void* cupsGetPrinters () { return 0; }
void* cupsGetResponse () { return 0; }
void* cupsGetServerPPD () { return 0; }
void* _cupsGlobalLock () { return 0; }
void* _cupsGlobals () { return 0; }
void* _cupsGlobalUnlock () { return 0; }
void* cupsHashData () { return 0; }
void* cupsHashString () { return 0; }
void* cupsHMACData () { return 0; }
void* cupsLangDefault () { return 0; }
void* cupsLangEncoding () { return 0; }
void* cupsLangFlush () { return 0; }
void* cupsLangFree () { return 0; }
void* cupsLangGet () { return 0; }
void* _cupsLangPrintError () { return 0; }
void* _cupsLangPrintf () { return 0; }
void* _cupsLangPrintFilter () { return 0; }
void* _cupsLangPuts () { return 0; }
void* _cupsLangString () { return 0; }
void* cupsLastError () { return 0; }
void* cupsLastErrorString () { return 0; }
void* cupsLocalizeDestMedia () { return 0; }
void* cupsLocalizeDestOption () { return 0; }
void* cupsLocalizeDestValue () { return 0; }
void* cupsMakeServerCredentials () { return 0; }
void* cupsMarkOptions () { return 0; }
void* _cupsMessageFree () { return 0; }
void* _cupsMessageLoad () { return 0; }
void* _cupsMessageLookup () { return 0; }
void* _cupsMessageNew () { return 0; }
void* _cupsMessageSave () { return 0; }
void* _cupsMutexInit () { return 0; }
void* _cupsMutexLock () { return 0; }
void* _cupsMutexUnlock () { return 0; }
void* _cupsNextDelay () { return 0; }
void* cupsNotifySubject () { return 0; }
void* cupsNotifyText () { return 0; }
void* cupsParseOptions () { return 0; }
void* cupsPrintFile () { return 0; }
void* cupsPrintFile2 () { return 0; }
void* cupsPrintFiles () { return 0; }
void* cupsPrintFiles2 () { return 0; }
void* cupsPutFd () { return 0; }
void* cupsPutFile () { return 0; }
void* _cupsRasterAddError () { return 0; }
void* _cupsRasterClearError () { return 0; }
void* cupsRasterClose () { return 0; }
void* _cupsRasterColorSpaceString () { return 0; }
void* _cupsRasterDelete () { return 0; }
void* _cupsRasterErrorString () { return 0; }
void* cupsRasterErrorString () { return 0; }
void* _cupsRasterExecPS () { return 0; }
void* _cupsRasterInitPWGHeader () { return 0; }
void* cupsRasterInitPWGHeader () { return 0; }
void* _cupsRasterInterpretPPD () { return 0; }
void* cupsRasterInterpretPPD () { return 0; }
void* _cupsRasterNew () { return 0; }
void* cupsRasterOpen () { return 0; }
void* cupsRasterOpenIO () { return 0; }
void* _cupsRasterReadHeader () { return 0; }
void* cupsRasterReadHeader () { return 0; }
void* cupsRasterReadHeader2 () { return 0; }
void* _cupsRasterReadPixels () { return 0; }
void* cupsRasterReadPixels () { return 0; }
void* _cupsRasterWriteHeader () { return 0; }
void* cupsRasterWriteHeader () { return 0; }
void* cupsRasterWriteHeader2 () { return 0; }
void* _cupsRasterWritePixels () { return 0; }
void* cupsRasterWritePixels () { return 0; }
void* cupsReadResponseData () { return 0; }
void* cupsRemoveDest () { return 0; }
void* cupsRemoveOption () { return 0; }
void* cupsResolveConflicts () { return 0; }
void* _cupsRWInit () { return 0; }
void* _cupsRWLockRead () { return 0; }
void* _cupsRWLockWrite () { return 0; }
void* _cupsRWUnlock () { return 0; }
void* _cups_safe_vsnprintf () { return 0; }
void* cupsSendRequest () { return 0; }
void* cupsServer () { return 0; }
void* cupsSetClientCertCB () { return 0; }
void* cupsSetCredentials () { return 0; }
void* cupsSetDefaultDest () { return 0; }
void* cupsSetDests () { return 0; }
void* cupsSetDests2 () { return 0; }
void* cupsSetEncryption () { return 0; }
void* _cupsSetError () { return 0; }
void* _cupsSetLocale () { return 0; }
void* cupsSetOAuthCB () { return 0; }
void* cupsSetPasswordCB () { return 0; }
void* cupsSetPasswordCB2 () { return 0; }
void* cupsSetServer () { return 0; }
void* cupsSetServerCertCB () { return 0; }
void* cupsSetServerCredentials () { return 0; }
void* cupsSetUser () { return 0; }
void* cupsSetUserAgent () { return 0; }
void* cupsSideChannelDoRequest () { return 0; }
void* cupsSideChannelRead () { return 0; }
void* cupsSideChannelSNMPGet () { return 0; }
void* cupsSideChannelSNMPWalk () { return 0; }
void* cupsSideChannelWrite () { return 0; }
void* _cupsSNMPClose () { return 0; }
void* _cupsSNMPCopyOID () { return 0; }
void* _cupsSNMPDefaultCommunity () { return 0; }
void* _cupsSNMPIsOID () { return 0; }
void* _cupsSNMPIsOIDPrefixed () { return 0; }
void* _cupsSNMPOIDToString () { return 0; }
void* _cupsSNMPOpen () { return 0; }
void* _cupsSNMPRead () { return 0; }
void* _cupsSNMPSetDebug () { return 0; }
void* _cupsSNMPStringToOID () { return 0; }
void* _cupsSNMPWalk () { return 0; }
void* _cupsSNMPWrite () { return 0; }
void* cupsStartDestDocument () { return 0; }
void* cupsStartDocument () { return 0; }
void* _cupsStrAlloc () { return 0; }
void* _cups_strcasecmp () { return 0; }
void* _cups_strcpy () { return 0; }
void* _cupsStrDate () { return 0; }
void* _cupsStrFlush () { return 0; }
void* _cupsStrFormatd () { return 0; }
void* _cupsStrFree () { return 0; }
void* _cups_strncasecmp () { return 0; }
void* _cupsStrRetain () { return 0; }
void* _cupsStrScand () { return 0; }
void* _cupsStrStatistics () { return 0; }
void* cupsTempFd () { return 0; }
void* cupsTempFile () { return 0; }
void* cupsTempFile2 () { return 0; }
void* _cupsThreadCancel () { return 0; }
void* _cupsThreadCreate () { return 0; }
void* _cupsThreadDetach () { return 0; }
void* _cupsThreadWait () { return 0; }
void* cupsUser () { return 0; }
void* cupsUserAgent () { return 0; }
void* cupsUTF32ToUTF8 () { return 0; }
void* cupsUTF8ToCharset () { return 0; }
void* cupsUTF8ToUTF32 () { return 0; }
void* cupsWriteRequestData () { return 0; }
void* httpAcceptConnection () { return 0; }
void* httpAddCredential () { return 0; }
void* httpAddrAny () { return 0; }
void* httpAddrClose () { return 0; }
void* httpAddrConnect () { return 0; }
void* httpAddrConnect2 () { return 0; }
void* httpAddrCopyList () { return 0; }
void* httpAddrEqual () { return 0; }
void* httpAddrFamily () { return 0; }
void* httpAddrFreeList () { return 0; }
void* httpAddrGetList () { return 0; }
void* httpAddrLength () { return 0; }
void* httpAddrListen () { return 0; }
void* httpAddrLocalhost () { return 0; }
void* httpAddrLookup () { return 0; }
void* httpAddrPort () { return 0; }
void* _httpAddrSetPort () { return 0; }
void* httpAddrString () { return 0; }
void* httpAssembleURI () { return 0; }
void* httpAssembleURIf () { return 0; }
void* httpAssembleUUID () { return 0; }
void* httpBlocking () { return 0; }
void* httpCheck () { return 0; }
void* httpClearCookie () { return 0; }
void* httpClearFields () { return 0; }
void* httpClose () { return 0; }
void* httpCompareCredentials () { return 0; }
void* httpConnect () { return 0; }
void* httpConnect2 () { return 0; }
void* httpConnectEncrypt () { return 0; }
void* httpCopyCredentials () { return 0; }
void* _httpCreateCredentials () { return 0; }
void* httpCredentialsAreValidForName () { return 0; }
void* httpCredentialsGetExpiration () { return 0; }
void* httpCredentialsGetTrust () { return 0; }
void* httpCredentialsString () { return 0; }
void* httpDecode64 () { return 0; }
void* httpDecode64_2 () { return 0; }
void* _httpDecodeURI () { return 0; }
void* httpDelete () { return 0; }
void* _httpDisconnect () { return 0; }
void* httpEncode64 () { return 0; }
void* httpEncode64_2 () { return 0; }
void* _httpEncodeURI () { return 0; }
void* httpEncryption () { return 0; }
void* httpError () { return 0; }
void* httpFieldValue () { return 0; }
void* httpFlush () { return 0; }
void* httpFlushWrite () { return 0; }
void* _httpFreeCredentials () { return 0; }
void* httpFreeCredentials () { return 0; }
void* httpGet () { return 0; }
void* httpGetActivity () { return 0; }
void* httpGetAddress () { return 0; }
void* httpGetAuthString () { return 0; }
void* httpGetBlocking () { return 0; }
void* httpGetContentEncoding () { return 0; }
void* httpGetCookie () { return 0; }
void* httpGetDateString () { return 0; }
void* httpGetDateString2 () { return 0; }
void* httpGetDateTime () { return 0; }
void* httpGetEncryption () { return 0; }
void* httpGetExpect () { return 0; }
void* httpGetFd () { return 0; }
void* httpGetField () { return 0; }
void* httpGetHostByName () { return 0; }
void* httpGetHostname () { return 0; }
void* httpGetKeepAlive () { return 0; }
void* httpGetLength () { return 0; }
void* httpGetLength2 () { return 0; }
void* httpGetPending () { return 0; }
void* httpGetReady () { return 0; }
void* httpGetRemaining () { return 0; }
void* httpGets () { return 0; }
void* httpGetState () { return 0; }
void* httpGetStatus () { return 0; }
void* httpGetSubField () { return 0; }
void* httpGetSubField2 () { return 0; }
void* httpGetVersion () { return 0; }
void* httpHead () { return 0; }
void* httpInitialize () { return 0; }
void* httpIsChunked () { return 0; }
void* httpIsEncrypted () { return 0; }
void* httpLoadCredentials () { return 0; }
void* httpMD5 () { return 0; }
void* httpMD5Final () { return 0; }
void* httpMD5String () { return 0; }
void* httpOptions () { return 0; }
void* httpPeek () { return 0; }
void* httpPost () { return 0; }
void* httpPrintf () { return 0; }
void* httpPut () { return 0; }
void* httpRead () { return 0; }
void* httpRead2 () { return 0; }
void* httpReadRequest () { return 0; }
void* httpReconnect () { return 0; }
void* httpReconnect2 () { return 0; }
void* httpResolveHostname () { return 0; }
void* _httpResolveURI () { return 0; }
void* httpSaveCredentials () { return 0; }
void* httpSeparate () { return 0; }
void* httpSeparate2 () { return 0; }
void* httpSeparateURI () { return 0; }
void* httpSetAuthString () { return 0; }
void* httpSetCookie () { return 0; }
void* httpSetCredentials () { return 0; }
void* httpSetDefaultField () { return 0; }
void* _httpSetDigestAuthString () { return 0; }
void* httpSetExpect () { return 0; }
void* httpSetField () { return 0; }
void* httpSetKeepAlive () { return 0; }
void* httpSetLength () { return 0; }
void* httpSetTimeout () { return 0; }
void* httpShutdown () { return 0; }
void* httpStateString () { return 0; }
void* _httpStatus () { return 0; }
void* httpStatus () { return 0; }
void* _httpTLSInitialize () { return 0; }
void* _httpTLSPending () { return 0; }
void* _httpTLSRead () { return 0; }
void* _httpTLSSetOptions () { return 0; }
void* _httpTLSStart () { return 0; }
void* _httpTLSStop () { return 0; }
void* _httpTLSWrite () { return 0; }
void* httpTrace () { return 0; }
void* _httpUpdate () { return 0; }
void* httpUpdate () { return 0; }
void* httpURIStatusString () { return 0; }
void* _httpWait () { return 0; }
void* httpWait () { return 0; }
void* httpWrite () { return 0; }
void* httpWrite2 () { return 0; }
void* httpWriteResponse () { return 0; }
void* ippAddBoolean () { return 0; }
void* ippAddBooleans () { return 0; }
void* ippAddCollection () { return 0; }
void* ippAddCollections () { return 0; }
void* ippAddDate () { return 0; }
void* ippAddInteger () { return 0; }
void* ippAddIntegers () { return 0; }
void* ippAddOctetString () { return 0; }
void* ippAddOutOfBand () { return 0; }
void* ippAddRange () { return 0; }
void* ippAddRanges () { return 0; }
void* ippAddResolution () { return 0; }
void* ippAddResolutions () { return 0; }
void* ippAddSeparator () { return 0; }
void* ippAddString () { return 0; }
void* ippAddStringf () { return 0; }
void* ippAddStringfv () { return 0; }
void* ippAddStrings () { return 0; }
void* ippAttributeString () { return 0; }
void* ippContainsInteger () { return 0; }
void* ippContainsString () { return 0; }
void* ippCopyAttribute () { return 0; }
void* ippCopyAttributes () { return 0; }
void* ippCreateRequestedArray () { return 0; }
void* ippDateToTime () { return 0; }
void* ippDelete () { return 0; }
void* ippDeleteAttribute () { return 0; }
void* ippDeleteValues () { return 0; }
void* ippEnumString () { return 0; }
void* ippEnumValue () { return 0; }
void* ippErrorString () { return 0; }
void* ippErrorValue () { return 0; }
void* _ippFileParse () { return 0; }
void* _ippFileReadToken () { return 0; }
void* ippFindAttribute () { return 0; }
void* ippFindNextAttribute () { return 0; }
void* _ippFindOption () { return 0; }
void* ippFirstAttribute () { return 0; }
void* ippGetBoolean () { return 0; }
void* ippGetCollection () { return 0; }
void* ippGetCount () { return 0; }
void* ippGetDate () { return 0; }
void* ippGetGroupTag () { return 0; }
void* ippGetInteger () { return 0; }
void* ippGetName () { return 0; }
void* ippGetOctetString () { return 0; }
void* ippGetOperation () { return 0; }
void* ippGetRange () { return 0; }
void* ippGetRequestId () { return 0; }
void* ippGetResolution () { return 0; }
void* ippGetState () { return 0; }
void* ippGetStatusCode () { return 0; }
void* ippGetString () { return 0; }
void* ippGetValueTag () { return 0; }
void* ippGetVersion () { return 0; }
void* ippLength () { return 0; }
void* ippNew () { return 0; }
void* ippNewRequest () { return 0; }
void* ippNewResponse () { return 0; }
void* ippNextAttribute () { return 0; }
void* ippOpString () { return 0; }
void* ippOpValue () { return 0; }
void* ippPort () { return 0; }
void* ippRead () { return 0; }
void* ippReadFile () { return 0; }
void* ippReadIO () { return 0; }
void* ippSetBoolean () { return 0; }
void* ippSetCollection () { return 0; }
void* ippSetDate () { return 0; }
void* ippSetGroupTag () { return 0; }
void* ippSetInteger () { return 0; }
void* ippSetName () { return 0; }
void* ippSetOctetString () { return 0; }
void* ippSetOperation () { return 0; }
void* ippSetPort () { return 0; }
void* ippSetRange () { return 0; }
void* ippSetRequestId () { return 0; }
void* ippSetResolution () { return 0; }
void* ippSetState () { return 0; }
void* ippSetStatusCode () { return 0; }
void* ippSetString () { return 0; }
void* ippSetStringf () { return 0; }
void* ippSetStringfv () { return 0; }
void* ippSetValueTag () { return 0; }
void* ippSetVersion () { return 0; }
void* ippStateString () { return 0; }
void* ippTagString () { return 0; }
void* ippTagValue () { return 0; }
void* ippTimeToDate () { return 0; }
void* ippValidateAttribute () { return 0; }
void* ippValidateAttributes () { return 0; }
void* _ippVarsDeinit () { return 0; }
void* _ippVarsExpand () { return 0; }
void* _ippVarsGet () { return 0; }
void* _ippVarsInit () { return 0; }
void* _ippVarsPasswordCB () { return 0; }
void* _ippVarsSet () { return 0; }
void* ippWrite () { return 0; }
void* ippWriteFile () { return 0; }
void* ippWriteIO () { return 0; }
void* _ppdCacheCreateWithFile () { return 0; }
void* _ppdCacheCreateWithPPD () { return 0; }
void* _ppdCacheDestroy () { return 0; }
void* _ppdCacheGetBin () { return 0; }
void* _ppdCacheGetFinishingOptions () { return 0; }
void* _ppdCacheGetFinishingValues () { return 0; }
void* _ppdCacheGetInputSlot () { return 0; }
void* _ppdCacheGetMediaType () { return 0; }
void* _ppdCacheGetOutputBin () { return 0; }
void* _ppdCacheGetPageSize () { return 0; }
void* _ppdCacheGetSize () { return 0; }
void* _ppdCacheGetSource () { return 0; }
void* _ppdCacheGetType () { return 0; }
void* _ppdCacheWriteFile () { return 0; }
void* ppdClose () { return 0; }
void* ppdCollect () { return 0; }
void* ppdCollect2 () { return 0; }
void* ppdConflicts () { return 0; }
void* _ppdCreateFromIPP () { return 0; }
void* _ppdCreateFromIPP2 () { return 0; }
void* ppdEmit () { return 0; }
void* ppdEmitAfterOrder () { return 0; }
void* ppdEmitFd () { return 0; }
void* ppdEmitJCL () { return 0; }
void* ppdEmitJCLEnd () { return 0; }
void* ppdEmitString () { return 0; }
void* ppdErrorString () { return 0; }
void* ppdFindAttr () { return 0; }
void* ppdFindChoice () { return 0; }
void* ppdFindCustomOption () { return 0; }
void* ppdFindCustomParam () { return 0; }
void* ppdFindMarkedChoice () { return 0; }
void* ppdFindNextAttr () { return 0; }
void* ppdFindOption () { return 0; }
void* ppdFirstCustomParam () { return 0; }
void* ppdFirstOption () { return 0; }
void* _ppdFreeLanguages () { return 0; }
void* _ppdGetEncoding () { return 0; }
void* _ppdGetLanguages () { return 0; }
void* _ppdGlobals () { return 0; }
void* _ppdHashName () { return 0; }
void* ppdInstallableConflict () { return 0; }
void* ppdIsMarked () { return 0; }
void* ppdLastError () { return 0; }
void* ppdLocalize () { return 0; }
void* ppdLocalizeAttr () { return 0; }
void* _ppdLocalizedAttr () { return 0; }
void* ppdLocalizeIPPReason () { return 0; }
void* ppdLocalizeMarkerName () { return 0; }
void* ppdMarkDefaults () { return 0; }
void* ppdMarkOption () { return 0; }
void* ppdNextCustomParam () { return 0; }
void* ppdNextOption () { return 0; }
void* _ppdNormalizeMakeAndModel () { return 0; }
void* _ppdOpen () { return 0; }
void* ppdOpen () { return 0; }
void* ppdOpen2 () { return 0; }
void* ppdOpenFd () { return 0; }
void* _ppdOpenFile () { return 0; }
void* ppdOpenFile () { return 0; }
void* ppdPageLength () { return 0; }
void* ppdPageSize () { return 0; }
void* ppdPageSizeLimits () { return 0; }
void* ppdPageWidth () { return 0; }
void* _ppdParseOptions () { return 0; }
void* ppdSetConformance () { return 0; }
void* pwgFormatSizeName () { return 0; }
void* pwgInitSize () { return 0; }
void* _pwgInputSlotForSource () { return 0; }
void* pwgMediaForLegacy () { return 0; }
void* pwgMediaForPPD () { return 0; }
void* pwgMediaForPWG () { return 0; }
void* pwgMediaForSize () { return 0; }
void* _pwgMediaNearSize () { return 0; }
void* _pwgMediaTable () { return 0; }
void* _pwgMediaTypeForType () { return 0; }
void* _pwgPageSizeForMedia () { return 0; }
